version: '23.0.4'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escrow-p2p-platform
    networks:
      - escrow-p2p-platform
    volumes:
      - ./db:/var/lib/postgresql/data
networks:
  escrow-p2p-platform:
